name       : gtkglext
version    : 1.2.0
release    : 1
source     :
    - http://downloads.sourceforge.net/gtkglext/gtkglext-1.2.0.tar.gz : e5073f3c6b816e7fa67d359d9745a5bb5de94a628ac85f624c992925a46844f9
license    : LGPL-2.1
summary    : GtkGLExt is an OpenGL extension to GTK+.
description: |
    GtkGLExt is an OpenGL extension to GTK+. It provides additional GDK objects which support OpenGL rendering in GTK+ and GtkWidget API add-ons to make GTK+ widgets OpenGL-capable.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(pangox)
    - pkgconfig(xmu)
libsplit : no
setup      : |
    %configure --disable-static --includedir=/usr/include/
build      : |
    %make
install    : |
    %make_install
